import Context from '@/context/context';
import './globals.css';
import TheHeader from '@/components/TheHeader/TheHeader';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">   
            <Context>
                  <body>{children}</body>
            </Context>
      </html>
    )
}


